name: "Run test actions"

on:
  push:
    branches:
      - 'master'
    paths-ignore: "docs/**"

jobs:
  run-cpp-lint-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'shenxianpeng',
            repo: 'test-action',
            workflow_id: 'cpp-lint-as-pkg.yml',
            ref: 'master'
          })
