name: Release

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to update to'
        default: 'v2'
        required: true
      ref:
        description: 'which branch to update the tag on'
        default: 'main'
        required: true

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.events.inputs.ref }}
    - name: update tag
      run: |
        git config user.name 'github-actions'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git tag --delete ${{ github.events.inputs.tag }}  || true
        git push --delete origin ${{ github.events.inputs.tag }} || true
        git tag -a ${{ github.events.inputs.tag }} -m 'Retag ${{ github.events.inputs.tag }}'
        git push origin ${{ github.events.inputs.tag }}
      # continue-on-error: true
