name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: echo "this is a test"
