name: test cpp-linter

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          lines-changed-only: true
          step-summary: true
          file-annotations: false
          version: 16
          tidy-checks: >-
            boost-*
            ,bugprone-*
            ,performance-*
            ,readability-*
            ,portability-*
            ,modernize-*
            ,clang-analyzer-*
            ,cppcoreguidelines-*
            ,-cppcoreguidelines-avoid-magic-numbers
            ,-readability-magic-numbers
            
#           # to ignore all build folder contents
#           ignore: build
#           # database: build
#           verbosity: 9
#           version: ${{ matrix.clang-version }}
#           thread-comments: ${{ matrix.clang-version == '12' }}
#           file-annotations: ${{ matrix.clang-version == '12' }}
#           extra-args: -std=c++14 -Wall

      - name: Fail fast?!
#       if: steps.linter.outputs.checks-failed > 0
        run: echo "${{ steps.linter.outputs.checks-failed }}"
        # for actual deployment
        # run: exit 1
